tarkuliTest/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tarkuli_project/', include('tarkuli_project.urls', namespace='tarkuli_project')),
]

tarkuli_project/urls.py
from django.conf.urls import url
from tarkuli_project import views
from django.contrib.auth import views as auth_view




urlpatterns = [
    
    url(r'^login/$', views.login, name='login'),    
    url(r'^logout/$', auth_view.logout, name="logout"),
    url(r'^manager/$', views.manager, name="manager"),
    url(r'^supervisor/$', views.supervisor, name="supervisor"),
    url(r'^supervisor2/$', views.supervisor2, name="supervisor2"),
    url(r'^employee/$', views.employee, name="employee"),
    url(r'^user_view/$', views.user_view, name="user_view"),

    url(r'^manager_view/(?P<y>\d+)/$', views.manager_view, name="manager_view"),
    ]

tarkuli_project/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class userModel(models.Model): 
    Firstname = models.CharField(max_length=25)
    Lastname = models.CharField(max_length=25)
    email = models.EmailField(max_length=70,blank=True, null= True, unique= True)
    password = models.CharField(max_length=25)
    Account = models.IntegerField()    
    Location = models.CharField(max_length=25)

    def __str__(self):
        return self.Firstname

tarkuli_project/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.shortcuts import render,redirect
from .models import userModel



def login(request):
    if 'e' in request.session: 
        e = request.session['e']
        return redirect('tarkuli_project:user_view')

    elif request.method == "POST":
        e = request.POST['email']
        p = request.POST['password']

        if (len(userModel.objects.filter(email=e)) and len(userModel.objects.filter(password=p))):
            request.session['e'] = e 
            # return render(request, 'tarkuli_project/user_view.html')
            return redirect('tarkuli_project:user_view')
    return render(request, 'tarkuli_project/login.html')


def manager(request):
	user_detail = userModel.objects.all()

	context = {
		'user_detail':user_detail,
		}
	return render(request,'tarkuli_project/manager.html',context)


def supervisor(request):
	user_detail = userModel.objects.filter(Location__in=['Delhi','Gurgaon'] )
	print(user_detail)

	context = {
		'user_detail':user_detail,
		}
	return render(request,'tarkuli_project/supervisor.html',context)



def supervisor2(request):
	user_detail = userModel.objects.filter(Location__in=['Jaipur','Kota'] )

	context = {
		'user_detail':user_detail,
		}
	return render(request,'tarkuli_project/supervisor2.html',context)

def employee(request):
	user_detail = userModel.objects.filter(Location='Delhi' )

	context = {
		'user_detail':user_detail,
		}
	return render(request,'tarkuli_project/employee.html',context)


def user_view(request):

	return render(request,'tarkuli_project/user_view.html')


def manager_view(request,y):
	user_view=userModel.objects.get(id=y)

	return render(request,'tarkuli_project/manager_view.html',{'detail':user_view})


	

tarkuli_project/templates/tarkuli_project/employee.html
<!DOCTYPE html>
<html>
<head>
	<title>Employee</title>
   <style>
  .bold{
    font-size: 35px;
  }
  </style>
</head>
<body>
	<form method="post">
	{% csrf_token %}
<a class="nav-link" href="{% url 'tarkuli_project:logout'%}">
                       <b class="bold"> Logout </b></a> 

     </form>

<table class="table">
  <thead>
    <tr>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Email</th>
      <th scope="col">Account</th>
      <th scope="col">Location</th>      
    </tr>
  </thead>
{% for detail in user_detail %}   

<tbody>
    <tr>
      <td>{{ detail.Firstname}}</td>
      <td>{{ detail.Lastname}}</td>
      <td>{{ detail.email}}</td>
      <td>{{ detail.Account}}</td>
      <td>{{ detail.Location}}</td>
    </tr>

{% endfor %}

</body>
</html>

tarkuli_project/templates/tarkuli_project/login.html
{% load static %}
<html>
<head>

    <meta charset="utf-8">
  <!-- <link rel="stylesheet" type="text/css" href="{% static 'first_site/style.css' %}"/> -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>

<style>
       #mycontainer{
        background:skyblue;
        width: 100%;
        margin:auto;
        padding: 10px;
    }
    .jumbotron{
        background: #333;   
        color: #fff;  
        background-size: cover; 
        height: 60%;  
    }
</style>
</head>
<div class="container" id="mycontainer">
    <div class="col-sm-8" style="width:600px; margin-left:250px; margin-top:50px;">

        <div class="jumbotron" >
            <div class="form-group" style="margin-top:-50px;">
                <h2 style="margin-left:150px;">User Login</h2>
            </div>
            <hr>
            <form class="form-horizontal" method="post" action="" style="margin-left:50px;">
                {% csrf_token %}
                <div class="form-group input-group">
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-user"></span>
                    </span>
                    <input type="email" class="form-control" name="email" placeholder="Enter email.." required>

                </div>
                <div class="form-group input-group">
                     <span class="input-group-addon">
                        <span class="glyphicon glyphicon-lock" aria-hidden="true"></span>
                    </span>

                    <input type="password" class="form-control" name="password" placeholder="Enter password..."
                           required>

                </div>
                <div class="form-group">
                    <label><input type="checkbox">Remenber me </label>
                </div>
                <div class="form-group">
                    <button class="btn btn-primary" style="width:430px;">Login</button>
                </div>
                

            </form>
        </div>
    </div>
</div>           

</html>

tarkuli_project/templates/tarkuli_project/manager.html
<!DOCTYPE html>
<html>
<head>
	<title>Manager</title>  
  <style>
  .bold{
    font-size: 35px;
  }
  </style>
</head>
<body>
	<form method="post">
	{% csrf_token %}
<a  href="{% url 'tarkuli_project:logout'%}">
                        <b class="bold">Logout</b></a> 

     </form>

<table class="table">
  <thead>
    <tr>
      <th >First Name</th>
      <th >Last Name</th>
      <th >Email</th>
      <th >Account</th>
      <th >Location</th>      
    </tr>
  </thead>
{% for detail in user_detail %}   
<tbody>
    <tr>
      <td><a href="{% url 'tarkuli_project:manager_view' detail.id %}">{{ detail.Firstname}}</td>
      <td>{{ detail.Lastname}}</td>
      <td>{{ detail.email}}</td>
      <td>{{ detail.Account}}</td>
      <td>{{ detail.Location}}</td>
    </tr>

{% endfor %}

</body>
</html>

tarkuli_project/templates/tarkuli_project/manager_view.html
<!DOCTYPE html>
<html>
<head>
	<title>See Detail by User Name</title>  
 
</head>
<body>



      <p>{{ detail.Firstname}}</p>
      <p>{{ detail.Lastname}}</p>
      <p>{{ detail.email}}</p>
      <p>{{ detail.Account}}</p>
      <p>{{ detail.Location}}</p>
 


</body>
</html>

tarkuli_project/templates/tarkuli_project/supervisor.html
<!DOCTYPE html>
<html>
<head>
	<title>Manager</title>
   <style>
  .bold{
    font-size: 35px;
  }
  </style>
</head>
<body>
	<form method="post">
	{% csrf_token %}
<a class="nav-link" href="{% url 'tarkuli_project:logout'%}">
                        <b class="bold">Logout</b> </a> 

     </form>

<table class="table">
  <thead>
    <tr>
      <th >First Name</th>
      <th >Last Name</th>
      <th >Email</th>
      <th >Account</th>
      <th >Location</th>      
    </tr>
  </thead>
{% for detail in user_detail %}   

<tbody>
    <tr>
      <td>{{ detail.Firstname}}</td>
      <td>{{ detail.Lastname}}</td>
      <td>{{ detail.email}}</td>
      <td>{{ detail.Account}}</td>
      <td>{{ detail.Location}}</td>
    </tr>

{% endfor %}

</body>
</html>

tarkuli_project/templates/tarkuli_project/supervisor2.html
<!DOCTYPE html>
<html>
<head>
	<title>SuperVisor</title>
   <style>
  .bold{
    font-size: 35px;
  }
  </style>
</head>
<body>
	<form method="post">
	{% csrf_token %}
<a class="nav-link" href="{% url 'tarkuli_project:logout'%}">
                        <b class="bold">Logout </b></a> 

     </form>

<table class="table">
  <thead>
    <tr>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Email</th>
      <th scope="col">Account</th>
      <th scope="col">Location</th>      
    </tr>
  </thead>
{% for detail in user_detail %}   

<tbody>
    <tr>
      <td>{{ detail.Firstname}}</td>
      <td>{{ detail.Lastname}}</td>
      <td>{{ detail.email}}</td>
      <td>{{ detail.Account}}</td>
      <td>{{ detail.Location}}</td>
    </tr>

{% endfor %}

</body>
</html>

tarkuli_project/templates/tarkuli_project/user_view.html
<!DOCTYPE html>
<html>
<head>
	<title>View</title>
</head>
<body>
<h1>Success</h1>
<form method="post">
	{% csrf_token %}
<a class="nav-link" href="{% url 'tarkuli_project:logout'%}">
                        Logout <span
                        class="sr-only"></span></a> 
<table>
	<tr>
		<td>
     <button type="button" value="Manager"> <a class="nav-link" href="{%url 'tarkuli_project:manager'%}">Manager </button><br>
     	</td>
     <td>
     <button type="button" value="Supervisor"><a class="nav-link" href="{%url 'tarkuli_project:supervisor'%}"> Supervisor </button><br>
 	</td>
 	<td>
     <button type="button" value="Supervisor 1"> 
        <a class="nav-link" href="{%url 'tarkuli_project:supervisor2'%}">Supervisor 1 </button><br>
 	</td>
 	<td>
     <button type="button" value="Employee"><a class="nav-link" href="{%url 'tarkuli_project:employee'%}"> Employee </button><br>
 </td>

</table>
</form>

</body>
</html>